Entities/Post.cs
using CourseWorkSpring2023.Abstract;
using System;
using System.Collections;
using System.Collections.Generic;

namespace CourseWorkSpring2023.Entities
{
    public class Post : UploadableContent
    {
        public string Header { get; set; }

        public string Text { get; set; }

        public List<PostsTags> Tags { get; set; }

        public List<Comment> Comments { get; set; }
    }
}

Models/HomeViewModels/HomeViewModel.cs
using CourseWorkSpring2023.Abstract;
using CourseWorkSpring2023.Entities;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace CourseWorkSpring2023.Models.HomeViewModels
{
    public class HomeViewModel
    {
        public HomeViewModel()
        {
        }

        public IEnumerable<PostViewModel> Posts { get; set; }

        public CustomUser ActiveUser { get; set; }

        public IEnumerable<int> UpvotedPostsIds { get; set; }

        public IEnumerable<int> DownvotedPostsIds { get; set; }
    }
}

Models/HomeViewModels/PostViewModel.cs
using CourseWorkSpring2023.Entities;
using Microsoft.AspNetCore.Html;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace CourseWorkSpring2023.Models.HomeViewModels
{
    public class PostViewModel
    {
        public PostViewModel()
        {

        }
        public PostViewModel(Post post)
        {
            Id = post.Id;
            Header = post.Header;
            RawText = post.Text;
            Upvotes = post.Upvotes;
            Downvotes = post.Downvotes;
            Posted = post.Uploaded;
            Tags = post.Tags;
            Author = post.User;
            IsHidden = post.IsHidden;
            Comments = post.Comments;

            ProcessedText = new HtmlString(RawText);
        }

        public int Id { get; }

        [Required(ErrorMessage = "Заголовок обязателен")]
        [Display(Name = "Заголовок")]
        [StringLength(10, ErrorMessage = "Ограничение на 250 символов")]
        public string Header { get; set; }

        [StringLength(250, ErrorMessage = "Ограничение на 250 символов")]
        public string RawText { get; set; }

        public HtmlString ProcessedText { get; set; }

        public int Upvotes { get; set; }

        public int Downvotes { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime Posted { get; set; }

        public IEnumerable<PostsTags> Tags { get; set; }
        public IEnumerable<Comment> Comments { get; set; }
        public bool IsHidden { get; }
        public CustomUser Author { get; set; }

        public int Rating
        {
            get { return Upvotes - Downvotes; }
        }

        public CustomUser ActiveUser { get; set; }

        public int CommentsCount
        {
            get
            {
                return Comments != null ? Comments.Count() : 0;
            }
        }

        public IEnumerable<int> UpvotedCommentsIds { get; set; }

        public IEnumerable<int> DownvotedCommentsIds { get; set; }

    }
}

Models/IndexViewModel/PostViewModel.cs
using CourseWorkSpring2023.Entities;
using Microsoft.AspNetCore.Html;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace CourseWorkSpring2023.Models.IndexViewModel
{
    public class PostViewModel
    {
        public PostViewModel()
        {

        }
        public PostViewModel(Post post)
        {
            Id = post.Id;
            Header = post.Header;
            RawText = post.Text;
            Upvotes = post.Upvotes;
            Downvotes = post.Downvotes;
            Posted = post.Uploaded;
            Tags = post.Tags;
            Author = post.User;
            IsHidden = post.IsHidden;
            Comments = post.Comments;
            UserAvatar = post.UserAvatarPath;

            ProcessedText = new HtmlString(RawText);
        }

        public int Id { get; }

        [Required(ErrorMessage = "Заголовок обязателен")]
        [Display(Name = "Заголовок")]
        [StringLength(100, ErrorMessage = "Ограничение на 100 символов")]
        public string Header { get; set; }

        [StringLength(5000, ErrorMessage = "Ограничение на 5000 символов")]
        [Display(Name = "Текст")]
        public string RawText { get; set; }

        public HtmlString ProcessedText { get; set; }

        public int Upvotes { get; set; }

        public int Downvotes { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime Posted { get; set; }

        public IEnumerable<PostsTags> Tags { get; set; }
        public IEnumerable<Comment> Comments { get; set; }
        public string UserAvatar { get; }
        public bool IsHidden { get; }
        public CustomUser Author { get; set; }

        public int Rating
        {
            get { return Upvotes - Downvotes; }
        }

        public CustomUser ActiveUser { get; set; }

        public int CommentsCount
        {
            get
            {
                return Comments != null ? Comments.Count() : 0;
            }
        }

        public IEnumerable<int> UpvotedCommentsIds { get; set; }

        public IEnumerable<int> DownvotedCommentsIds { get; set; }

    }
}

Componentes/ModeratorToolsViewComponent.cs
using CourseWorkSpring2023.Entities;
using CourseWorkSpring2023.Models.Moderator;
using Microsoft.AspNetCore.Mvc;
using System.Net.Mime;

namespace CourseWorkSpring2023.Componentes
{
    public class ModeratorToolsViewComponent : ViewComponent
    {
        public ModeratorToolsViewComponent() {}

        public IViewComponentResult Invoke(string ContentType, int Id)
        {
            var model = new ModeratorToolsViewModel()
            {
                ContentType = ContentType,
                Id = Id
            };
            return View(model);
        }
    }
}

Componentes/PostsFilterViewComponent.cs
using CourseWorkSpring2023.Constants;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace CourseWorkSpring2023.Componentes
{
    public class PostsFilterViewComponent : ViewComponent
    {
        public PostsFilterViewComponent() { }

        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using CourseWorkSpring2023.Abstract;
using CourseWorkSpring2023.Constants;
using CourseWorkSpring2023.Entities;
using CourseWorkSpring2023.Data.Migrations;
using CourseWorkSpring2023.DataAccessLayer;
using CourseWorkSpring2023.Models;
using CourseWorkSpring2023.Models.IndexViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using NuGet.Protocol.Core.Types;

namespace CourseWorkSpring2023.Controllers
{
    public class HomeController : Controller
    {
        private PostsRepository postsManager;
        private UserManager<CustomUser> userManager;
        private RatingsRepository ratingsManager;
        private ContentRepository contentManager;
        private CommentsRepository commentsManager;

        public HomeController(PostsRepository postsManager, UserManager<CustomUser> userManager, 
            RatingsRepository ratingsManager, ContentRepository contentManager, 
            CommentsRepository commentsRepository)
        {
            this.postsManager = postsManager;
            this.userManager = userManager;
            this.ratingsManager = ratingsManager;
            this.contentManager = contentManager;
            this.commentsManager = commentsRepository;
        }

        private async Task<CustomUser> GetUser()
        {
            return await userManager.GetUserAsync(User);
        }

        public async Task<JsonResult> GetAjax()
        {
            /// сделать обработку 
            /// разработать наш протокол
            /// 
            int id = 0;
            if (Request.Form.ContainsKey("Id"))
            {
               id  = int.Parse(Request.Form["Id"]);
            }
            CustomUser user = await GetUser();

           /* switch (Request.Form["Action"])
            {
                case "upvote":
                    {
                        ratingsManager.Upvote(id, user);
                        return Json(new { reply = 200 });
                    }
                case "downvote":
                    {
                        ratingsManager.Downvote(id, user);
                        return Json(new { reply = 200 });
                    }
                case "remove_downvote":
                    {
                        ratingsManager.RemoveDownvote(id, user);
                        return Json(new { reply = 200 });
                    }
                case "remove_upvote":
                    {
                        ratingsManager.RemoveUpvote(id, user);
                        return Json(new { reply = 200 });
                    }
                case "downvote_and_remove_upvote":
                    {
                        ratingsManager.DownvoteAndRemoveUpvote(id, user);
                        return Json(new { reply = 200 });
                    }
                case "upvote_and_remove_downvote":
                    {
                        ratingsManager.UpvoteAndRemoveDownvote(id, user);
                        return Json(new { reply = 200 });
                    }
                case "comment":
                    {
                       /* int postId = int.Parse(Request.Form["PostId"]);
                        int commentId = postsManager.AddComment(user, postId, Request.Form["Text"]);
                        return Json(new { reply = 200, commentId = commentId.ToString(), username = user.NickName });
                       return Json(new { reply = 200 });
                    }
                case "hide":
                    {
                        contentManager.Hide(id);
                        return Json(new { reply = 200 });
                    }
                case "unhide":
                    {
                        contentManager.UnHide(id);
                        return Json(new { reply = 200 });
                    }
                case "delete_post":
                    {
                        postsManager.Delete(id);
                        return Json(new { reply = 200 });
                    }
                case "delete_comment":
                    {
                        commentsManager.Delete(id);
                        return Json(new { reply = 200 });
                    }
                default:
                    return Json(new { reply = 400 }); */

            return Json(new { id, user });
        }
    }
}

Controllers/PostsController.cs
using CourseWorkSpring2023.Abstract;
using CourseWorkSpring2023.DataAccessLayer;
using CourseWorkSpring2023.Entities;
using CourseWorkSpring2023.Models.IndexViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace CourseWorkSpring2023.Controllers
{
    public class PostsController : Controller
    {
        private PostsRepository postsManager;
        private ICrud<PostsTags> tagsManager;
        private UserManager<CustomUser> userManager;
        private RatingsRepository ratingsManager;


        public PostsController(PostsRepository postsManager,
            ICrud<PostsTags> tagsManager, UserManager<CustomUser> userManager,
            RatingsRepository ratingsManager)
        {
            this.postsManager = postsManager;
            this.tagsManager = tagsManager;
            this.userManager = userManager;
            this.ratingsManager = ratingsManager;
        }

        private async Task<CustomUser> GetUser()
        {
            return await userManager.GetUserAsync(User);
        }

        public async Task<IActionResult> Index(int days = 0, string filter = null)
        {
            CustomUser user = await GetUser();
            var model = new IndexViewModel();

            if (user != null)
            {
                model.ActiveUser = user;
                model.UpvotedPostsIds = ratingsManager.UsersUpvotes(user).Select(p => p.Id);
                model.DownvotedPostsIds = ratingsManager.UsersDownvotes(user).Select(p => p.Id);
            }
            else
            {
                model.ActiveUser = null;
                model.UpvotedPostsIds = null;
                model.DownvotedPostsIds = null;
            }

            switch (filter)
            {
                case "top":
                    var rawPosts = postsManager.GetList().OrderByDescending(p => p.Upvotes).Select(p => new PostViewModel(p));
                    DateTime DaysFromToday = DateTime.Today.AddDays(-days);

                    model.Posts = rawPosts.Where(p => p.Posted > DaysFromToday);
                    return View(model);
                case "new":
                    model.Posts = postsManager.GetList().OrderByDescending(p => p.Uploaded).Select(p => new PostViewModel(p));
                    return View(model);
                case "follow":
                    model.Posts = postsManager.GetFollowedPosts(user).Select(p => new PostViewModel(p));
                    return View(model);
                case "popular":
                    model.Posts = postsManager.GetList().OrderByDescending(p => p.Comments.Count).Select(p => new PostViewModel(p));
                    return View(model);
                default:
                    model.Posts = postsManager.GetList().Select(p => new PostViewModel(p));
                    return View(model);
            }
        }


        public IActionResult CommentsOfPost(int postId)
        {
            var comments = postsManager.GetPostsComments(postId);
            return View(comments);
        }

        [Authorize]
        public IActionResult CreatePost()
        {
            var model = new PostViewModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreatePost(PostViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(nameof(CreatePost), model);
            }

            CustomUser user = await GetUser();

            var post = new Post()
            {
                Header = model.Header,
                Text = model.RawText,
                User = user,
                Downvotes = 0,
                Upvotes = 0,
                Uploaded = DateTime.Now,
            };

            postsManager.Create(post);
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> ReadPost(int postId)
        {
            var model = new PostViewModel(postsManager.Read(postId));
            model.Comments = postsManager.GetPostsComments(postId);
            CustomUser user = await GetUser();

            model.UpvotedCommentsIds = ratingsManager.UsersUpvotes(user).Select(p => p.Id);
            model.DownvotedCommentsIds = ratingsManager.UsersDownvotes(user).Select(p => p.Id);
            model.ActiveUser = user;
            return View(model);
        }
    }
}

Views/Home/CommentsOfPost.cshtml
@model IEnumerable<Comment>

@Html.ActionLink("Назад", "UserMainPage");
<div class="comment-section">
    @if (Model.Any())
    {
        @foreach (var comment in Model)
        {
            <div class="comment content">
            @await Component.InvokeAsync("ModeratorTools", new { ContentType = "comment", Id = comment.Id})
                    <h4>@comment.User.NickName</h4>
                    <p>@comment.ProcessedText</p>
                    <p>Рейтинг:</p>
                    <p>isHidden  -  @comment.IsHidden</p>
                    <p class="rating">@comment.Rating</p>
            </div>
        }
    }
    else
    {
        <div class="no-comments">
            <p>Комментариев пока нету</p>
        </div>
    }    
</div>

@section scripts{
        <script src="~/js/Moderator/Moderator.js" defer></script>
}

Views/Home/CreatePost.cshtml
@model CourseWorkSpring2023.Models.HomeViewModels.PostViewModel

@{
    ViewData["Title"] = "CreatePost";
}
<link rel="stylesheet" href="~/lib/Trumbowyg/dist/ui/trumbowyg.min.css">
<h1>Создайте пост</h1>

<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="CreatePost" method="post">
            <div class="form-group">
                <label asp-for="Header" class="control-label"></label>
                <input asp-for="Header" class="form-control" />
                <span asp-validation-for="Header" class="text-danger"></span>
            </div>
            <div class="form-group">
                <textarea asp-for="RawText" class="form-control"></textarea>
                <span asp-validation-for="RawText" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Запостить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="UserMainPage">Вернутся на главную</a>
</div>

@section scripts{
    <script src="~/lib/Trumbowyg/dist/trumbowyg.min.js"></script>
    <script src="~/lib/Trumbowyg/dist/langs/ru.js"></script>
    <script>
        $('#RawText').trumbowyg({
            lang: 'ru',
            tagsToRemove: ['script', 'link'],
            autogrow: true,
            autogrowOnEnter: true
        });
    </script>
}

Views/Home/Index.cshtml
@using CourseWorkSpring2023.Entities;
@using CourseWorkSpring2023.Models.HomeViewModels;
@using CourseWorkSpring2023.Models.Moderator;
@model HomeViewModel;
@{
    ViewData["Title"] = "Home Page";
}

@await Component.InvokeAsync("PostsFilter")

<div class="posts-container">
    @foreach (var post in Model.Posts)
    {
        <div class="post content">
            <div class="custom-post-info">
                <div>@Html.ActionLink(@post.Author.NickName, "UserPage", "Home", new { userName = post.Author.UserName})</div>
                <div>Дата публикации - @post.Posted</div>
            </div>

            <!--Пост спрятан - @post.IsHidden.ToString()-->
            

            @if (User.IsInRole("Moderator"))
                @await Component.InvokeAsync("ModeratorTools", new { ContentType = "post", Id = post.Id})

            <h2 class="custom-post-title">@post.Header</h2>
            
            <div class="custom-post-comments_count">
                Комментарии - @post.CommentsCount
            </div>
            
            <div class="custom-rate-btns">
            @if(Model.ActiveUser == null)
            {
                <a class="" asp-area="Identity" asp-page="/Account/Register"> <img src="~/icons/RatingIcon.svg"/></a>
                <div class="rating">@post.Rating</div>
                <a class="" asp-area="Identity" asp-page="/Account/Register"> <img src="~/icons/RatingIcon.svg"/> </a>
            }
            else
            {
                @if (Model.UpvotedPostsIds.Contains(post.Id))
                {
                    <div class="likeBtn" data-isPicked="true" data-Id=@post.Id data-action="remove_upvote">
                        <img src="~/icons/RatingIcon.svg"/>
                        </div>
                    <div class="rating">@post.Rating</div>
                    <div class="dislikeBtn" data-isPicked="false" data-Id=@post.Id data-action="downvote_and_remove_upvote">
                        <img src="~/icons/RatingIcon.svg"/>
                    </div>
                }
                else if (Model.DownvotedPostsIds.Contains(post.Id))
                {
                    <div class="likeBtn" data-isPicked="false" data-Id=@post.Id data-action="upvote_and_remove_downvote">
                        <img src="~/icons/RatingIcon.svg"/>
                    </div>
                    <div class="rating">@post.Rating</div>
                    <div class="dislikeBtn" data-isPicked="true" data-Id=@post.Id data-action="remove_downvote">
                        <img src="~/icons/RatingIcon.svg"/>
                    </div>
                }
                else
                {
                    <div class="likeBtn" data-isPicked="false" data-Id=@post.Id data-action="upvote">
                        <img src="~/icons/RatingIcon.svg"/>
                    </div>
                    <div class="rating">@post.Rating</div>
                    <div class="dislikeBtn" data-isPicked="false" data-Id=@post.Id data-action="downvote">
                        <img src="~/icons/RatingIcon.svg"/>
                    </div>
                }
            }
            </div>
            <a class="custom-post-open custom-red_btn" asp-action="Post" asp-route-postId=@post.Id>Открыть</a>
        </div>
    }
</div>

<a href="#logo" class="custom-go_top_btn custom-red_btn">
    Наверх
</a>

@section scripts{
    <script src="~/js/CommonActions/ratings.js"></script>
}

Views/Home/Post.cshtml
@using CourseWorkSpring2023.Models.HomeViewModels;
@using CourseWorkSpring2023.Models.Moderator;
@model PostViewModel
<link rel="stylesheet" href="~/lib/Trumbowyg/dist/ui/trumbowyg.min.css">
<div class="row">
    <div class="col-md-12">
    <h1>@Model.Header</h1>
    <h2>@Html.ActionLink(Model.Author.NickName, "UserPage", "Home", new { userName = Model.Author.UserName})</h2>
    <p class="postId" hidden>@Model.Id</p>
    <div>@Model.ProcessedText</div>

         <textarea id="RawText" class="comment_text"></textarea>
         <br>
         @if(Model.ActiveUser == null){
            <a class="btn btn-secondary" asp-area="Identity" asp-page="/Account/Register">Оставить комментарий</a>
         }
         else{
            <button class="leave_comment_btn btn btn-primary" data-Nickname=@Model.ActiveUser.NickName>Оставить комментарий</button>
         }
    <style>
        .comment-section .comment{
            border: 1px solid black;
            margin:5px;
            padding:5px;
        }
    </style>

    <div class="comment-section">
        @if(Model.Comments.Any()){
            @foreach (var comment in Model.Comments)
            {
                <div class="comment content">
                    @if (User.IsInRole("Moderator"))
                        @await Component.InvokeAsync("ModeratorTools", new { ContentType = "comment", Id = comment.Id})

                    <h4>@Html.ActionLink(comment.User.NickName, "UserPage", "Home", new { userName = comment.User.UserName})</h4>
                    <p>@comment.ProcessedText</p>
                    <p>Рейтинг:</p>
                    <p>isHidden  -  @comment.IsHidden</p>
                    <p class="rating">@comment.Rating</p>
            
                @if(Model.ActiveUser == null)
                {
                    <a class="btn btn-secondary" asp-area="Identity" asp-page="/Account/Register">+</a>
                    <a class="btn btn-secondary" asp-area="Identity" asp-page="/Account/Register">-</a>
                }
                else
                {
                    @if (Model.UpvotedCommentsIds.Contains(comment.Id))
                    {
                        <button class="btn btn-warning likeBtn"   data-isPicked="true"  data-Id=@comment.Id data-action="remove_upvote">+</button>
                        <button class="btn btn-secondary dislikeBtn" data-isPicked="false" data-Id=@comment.Id data-action="downvote_and_remove_upvote">-</button>
                    }
                    else if (Model.DownvotedCommentsIds.Contains(comment.Id))
                    {
                        <button class="btn btn-secondary likeBtn" data-isPicked="false" data-Id=@comment.Id data-action="upvote_and_remove_downvote">+</button>
                        <button class="btn btn-warning dislikeBtn"   data-isPicked="true" data-Id=@comment.Id data-action="remove_downvote">-</button>
                    }
                    else
                    {
                        <button class="btn btn-secondary likeBtn" data-isPicked="false" data-Id=@comment.Id data-action="upvote">+</button>
                        <button class="btn btn-secondary dislikeBtn" data-isPicked="false" data-Id=@comment.Id data-action="downvote">-</button>
                    }
                }
                </div>
            }
        }else{
            <div class="no-comments">
                <p>Комментариев пока нету</p>
            </div>
        }    
        </div>
</div>
</div>


@section scripts{

    <script src="~/lib/Trumbowyg/dist/trumbowyg.min.js"></script>
    <script src="~/lib/Trumbowyg/dist/langs/ru.js"></script>
    <script>
        $('#RawText').trumbowyg({
            lang: 'ru',
            tagsToRemove: ['script', 'link'],
            autogrow: true,
            autogrowOnEnter: true,
            btns:[
                ['formatting'],
                ['strong', 'em', 'del'],
                ['superscript', 'subscript'],
                ['unorderedList', 'orderedList'],
                ['horizontalRule'],
                ['removeformat'],
                ['fullscreen']
            ]
        });
    </script>
    <script src="~/js/CommonActions/ratings.js"></script>
    <script src="~/js/CommonActions/comment.js"></script>
}

Views/Home/UserMainPage.cshtml
@model UserViewModel

<h2>Hi @Model.NickName! Have a nice day!</h2>
<br>
<img src="@Model.AvatarImagePath" width="100" height="100"/>

<a asp-area="Identity" asp-page="/Account/Manage/Index">Управление акккаунтом</a>
<a asp-action="CreatePost">Post</a>

<style>
    .post{
        border: black solid 1px;
        margin: 20px;
    }
</style>

<div class="posts-container">
    @if (Model.Posts.Any())
    {
        @foreach (var post in Model.Posts)
        {
            <div class="post content">
                @await Component.InvokeAsync("ModeratorTools", new { ContentType = "post", Id = post.Id})
                <br>
                @post.Header
                <br>
                Дата публикации - @post.Posted
                <br>
                Комментарии - @post.CommentsCount
                <br>
                Пост спрятан - @post.IsHidden
                <p class="rating">@post.Rating</p>
                <a class="btn btn-primary" asp-action="CommentsOfPost" asp-route-postId="@post.Id">Открыть комментарии</a>
            </div>
        }

    }
    else
    {
        <p>У вас пока нет постов</p>
        <a asp-action="CreatePost">Post</a>
    }
</div>

@section scripts{
        <script src="~/js/Moderator/Moderator.js" defer></script>
}