Entities/Post.cs
using CourseWorkSpring2023.Abstract;
using System;
using System.Collections;
using System.Collections.Generic;

namespace CourseWorkSpring2023.Entities
{
    public class Post : UploadableContent
    {
        public string Header { get; set; }

        public string Text { get; set; }

        public List<PostsTags> Tags { get; set; }

        public List<Comment> Comments { get; set; }
    }
}

Models/HomeViewModels/PostViewModel.cs
using CourseWorkSpring2023.Entities;
using Microsoft.AspNetCore.Html;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace CourseWorkSpring2023.Models.HomeViewModels
{
    public class PostViewModel
    {
        public PostViewModel()
        {

        }
        public PostViewModel(Post post)
        {
            Id = post.Id;
            Header = post.Header;
            RawText = post.Text;
            Upvotes = post.Upvotes;
            Downvotes = post.Downvotes;
            Posted = post.Uploaded;
            Tags = post.Tags;
            Author = post.User;
            IsHidden = post.IsHidden;
            Comments = post.Comments;

            ProcessedText = new HtmlString(RawText);
        }

        public int Id { get; }

        [Required(ErrorMessage = "Заголовок обязателен")]
        [Display(Name = "Заголовок")]
        [StringLength(10, ErrorMessage = "Ограничение на 250 символов")]
        public string Header { get; set; }

        [StringLength(250, ErrorMessage = "Ограничение на 250 символов")]
        public string RawText { get; set; }

        public HtmlString ProcessedText { get; set; }

        public int Upvotes { get; set; }

        public int Downvotes { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime Posted { get; set; }

        public IEnumerable<PostsTags> Tags { get; set; }
        public IEnumerable<Comment> Comments { get; set; }
        public bool IsHidden { get; }
        public CustomUser Author { get; set; }

        public int Rating
        {
            get { return Upvotes - Downvotes; }
        }

        public CustomUser ActiveUser { get; set; }

        public int CommentsCount
        {
            get
            {
                return Comments != null ? Comments.Count() : 0;
            }
        }

        public IEnumerable<int> UpvotedCommentsIds { get; set; }

        public IEnumerable<int> DownvotedCommentsIds { get; set; }

    }
}

Models/IndexViewModel/PostViewModel.cs
using CourseWorkSpring2023.Entities;
using Microsoft.AspNetCore.Html;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace CourseWorkSpring2023.Models.IndexViewModel
{
    public class PostViewModel
    {
        public PostViewModel()
        {

        }
        public PostViewModel(Post post)
        {
            Id = post.Id;
            Header = post.Header;
            RawText = post.Text;
            Upvotes = post.Upvotes;
            Downvotes = post.Downvotes;
            Posted = post.Uploaded;
            Tags = post.Tags;
            Author = post.User;
            IsHidden = post.IsHidden;
            Comments = post.Comments;
            UserAvatar = post.UserAvatarPath;

            ProcessedText = new HtmlString(RawText);
        }

        public int Id { get; }

        [Required(ErrorMessage = "Заголовок обязателен")]
        [Display(Name = "Заголовок")]
        [StringLength(100, ErrorMessage = "Ограничение на 100 символов")]
        public string Header { get; set; }

        [StringLength(5000, ErrorMessage = "Ограничение на 5000 символов")]
        [Display(Name = "Текст")]
        public string RawText { get; set; }

        public HtmlString ProcessedText { get; set; }

        public int Upvotes { get; set; }

        public int Downvotes { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime Posted { get; set; }

        public IEnumerable<PostsTags> Tags { get; set; }
        public IEnumerable<Comment> Comments { get; set; }
        public string UserAvatar { get; }
        public bool IsHidden { get; }
        public CustomUser Author { get; set; }

        public int Rating
        {
            get { return Upvotes - Downvotes; }
        }

        public CustomUser ActiveUser { get; set; }

        public int CommentsCount
        {
            get
            {
                return Comments != null ? Comments.Count() : 0;
            }
        }

        public IEnumerable<int> UpvotedCommentsIds { get; set; }

        public IEnumerable<int> DownvotedCommentsIds { get; set; }

    }
}

Componentes/PostsFilterViewComponent.cs
using CourseWorkSpring2023.Constants;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace CourseWorkSpring2023.Componentes
{
    public class PostsFilterViewComponent : ViewComponent
    {
        public PostsFilterViewComponent() { }

        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Controllers/PostsController.cs
using CourseWorkSpring2023.Abstract;
using CourseWorkSpring2023.DataAccessLayer;
using CourseWorkSpring2023.Entities;
using CourseWorkSpring2023.Models.IndexViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace CourseWorkSpring2023.Controllers
{
    public class PostsController : Controller
    {
        private PostsRepository postsManager;
        private ICrud<PostsTags> tagsManager;
        private UserManager<CustomUser> userManager;
        private RatingsRepository ratingsManager;


        public PostsController(PostsRepository postsManager,
            ICrud<PostsTags> tagsManager, UserManager<CustomUser> userManager,
            RatingsRepository ratingsManager)
        {
            this.postsManager = postsManager;
            this.tagsManager = tagsManager;
            this.userManager = userManager;
            this.ratingsManager = ratingsManager;
        }

        private async Task<CustomUser> GetUser()
        {
            return await userManager.GetUserAsync(User);
        }

        public async Task<IActionResult> Index(int days = 0, string filter = null)
        {
            CustomUser user = await GetUser();
            var model = new IndexViewModel();

            if (user != null)
            {
                model.ActiveUser = user;
                model.UpvotedPostsIds = ratingsManager.UsersUpvotes(user).Select(p => p.Id);
                model.DownvotedPostsIds = ratingsManager.UsersDownvotes(user).Select(p => p.Id);
            }
            else
            {
                model.ActiveUser = null;
                model.UpvotedPostsIds = null;
                model.DownvotedPostsIds = null;
            }

            switch (filter)
            {
                case "top":
                    var rawPosts = postsManager.GetList().OrderByDescending(p => p.Upvotes).Select(p => new PostViewModel(p));
                    DateTime DaysFromToday = DateTime.Today.AddDays(-days);

                    model.Posts = rawPosts.Where(p => p.Posted > DaysFromToday);
                    return View(model);
                case "new":
                    model.Posts = postsManager.GetList().OrderByDescending(p => p.Uploaded).Select(p => new PostViewModel(p));
                    return View(model);
                case "follow":
                    model.Posts = postsManager.GetFollowedPosts(user).Select(p => new PostViewModel(p));
                    return View(model);
                case "popular":
                    model.Posts = postsManager.GetList().OrderByDescending(p => p.Comments.Count).Select(p => new PostViewModel(p));
                    return View(model);
                default:
                    model.Posts = postsManager.GetList().Select(p => new PostViewModel(p));
                    return View(model);
            }
        }


        public IActionResult CommentsOfPost(int postId)
        {
            var comments = postsManager.GetPostsComments(postId);
            return View(comments);
        }

        [Authorize]
        public IActionResult CreatePost()
        {
            var model = new PostViewModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreatePost(PostViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(nameof(CreatePost), model);
            }

            CustomUser user = await GetUser();

            var post = new Post()
            {
                Header = model.Header,
                Text = model.RawText,
                User = user,
                Downvotes = 0,
                Upvotes = 0,
                Uploaded = DateTime.Now,
            };

            postsManager.Create(post);
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> ReadPost(int postId)
        {
            var model = new PostViewModel(postsManager.Read(postId));
            model.Comments = postsManager.GetPostsComments(postId);
            CustomUser user = await GetUser();

            model.UpvotedCommentsIds = ratingsManager.UsersUpvotes(user).Select(p => p.Id);
            model.DownvotedCommentsIds = ratingsManager.UsersDownvotes(user).Select(p => p.Id);
            model.ActiveUser = user;
            return View(model);
        }
    }
}

Controllers/UserController.cs
using CourseWorkSpring2023.Abstract;
using CourseWorkSpring2023.DataAccessLayer;
using CourseWorkSpring2023.Entities;
using CourseWorkSpring2023.Models;
using CourseWorkSpring2023.Models.IndexViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace CourseWorkSpring2023.Controllers
{
    public class UserController : Controller
    {
        private PostsRepository postsManager;
        private UserManager<CustomUser> userManager;
        private FollowersRepository followersManager;

        public UserController(PostsRepository postsManager, UserManager<CustomUser> userManager,FollowersRepository followersManager)
        {
            this.postsManager = postsManager;
            this.userManager = userManager;
            this.followersManager = followersManager;
        }

        private async Task<CustomUser> GetUser()
        {
            return await userManager.GetUserAsync(User);
        }

        [Authorize]
        public async Task<IActionResult> UserMainPage()
        {
            var user = await GetUser();

            var model = new UserViewModel(user);
            model.Posts = postsManager.GetUsersPosts(user).Select(p => new PostViewModel(p));
            return View(model);
        }

        public async Task<IActionResult> UserPage(string userName)
        {
            var user = await userManager.FindByNameAsync(userName);
            UserViewModel model = new UserViewModel(user);
            model.FollowersIds = followersManager.UserFollowers(user.Id);
            model.Posts = postsManager.GetUsersPosts(user.Id).Select(p => new PostViewModel(p));

            return View(model);
        }

        public async Task<IActionResult> FollowTest(string userId)
        {
            var follower = await GetUser();

            followersManager.FollowUser(follower.Id, userId);

            return RedirectToAction("Index");

        }
    }
}

Views/Posts/CreatePost.cshtml
@model CourseWorkSpring2023.Models.IndexViewModel.PostViewModel

@{
    ViewData["Title"] = "CreatePost";
}

<h1>Создайте пост</h1>

<hr />
<div class="custom-post_form">
        <form asp-action="CreatePost" method="post">
            <div class="title">
                <label asp-for="Header"></label>
                <input class="custom-post_form_title" asp-for="Header"/>
                <span class="text-danger" asp-validation-for="Header"></span>
            </div>
            <div class="text">
                <label class="label_text" asp-for="RawText"></label>
                <textarea asp-for="RawText"></textarea>
                <span class="text-danger" asp-validation-for="RawText"></span>
            </div>
            <div class="btns">
                <input type="submit" value="Запостить" class="custom-red_btn create_post" />
                 <a class="custom-red_btn" asp-controller="User" asp-action="UserMainPage">Вернутся на главную</a>
            </div>
        </form>
</div>

@section scripts{
    <script src="~/lib/Trumbowyg/dist/trumbowyg.min.js"></script>
    <script src="~/lib/Trumbowyg/dist/langs/ru.js"></script>
    <script>
        $('#RawText').trumbowyg({
            lang: 'ru',
            tagsToRemove: ['script', 'link'],
            autogrow: true,
            autogrowOnEnter: true
        });
    </script>
}


@section AddToHead{
    <link rel="stylesheet" href="~/lib/Trumbowyg/dist/ui/trumbowyg.min.css">
    <link rel="stylesheet" href="~/css/create_post.css"/>
}

Views/Posts/Index.cshtml
@using CourseWorkSpring2023.Entities;
@using CourseWorkSpring2023.Models.IndexViewModel;
@using CourseWorkSpring2023.Models.Moderator;
@model IndexViewModel;
@{
    ViewData["Title"] = "Home Page";
    string HiddenPostStyle = string.Empty;
}

@await Component.InvokeAsync("PostsFilter")

<div class="posts-container">
    @foreach (var post in Model.Posts)
    {
        @if(!User.IsInRole("Moderator") && post.IsHidden)
        {
            continue;
        }
        

        <div class="post content @HiddenPostStyle" id="@post.Id">
            @if (User.IsInRole("Moderator"))
            {
                @(await Html.RenderComponentAsync<CourseWorkSpring2023.BlazorComponents.
                ModeratorTools>(RenderMode.ServerPrerendered,new { ContentType = "post", Id = post.Id, IsHidden = post.IsHidden}))
                if(post.IsHidden){
                    HiddenPostStyle = "custom-postIsHidden";
                }
                else
                {
                    HiddenPostStyle = string.Empty;
                }
            }
            <div class="custom-post-info">
                @if(post.Author.Email == User.Identity.Name)
                {
                    <div>@Html.ActionLink(@post.Author.NickName, "UserMainPage", "User", new { userName = post.Author.UserName})</div>
                }
                else
                {
                    <div>@Html.ActionLink(@post.Author.NickName, "UserPage", "User", new { userName = post.Author.UserName})</div>
                }
                
                <div>Дата публикации - @post.Posted</div>
            </div>
            



            <h2 class="custom-post-title">@post.Header</h2>
            
            <div class="custom-post-comments_count">
                Комментарии - @post.CommentsCount
            </div>
            
            <div class="custom-rate-btns">
            @if(Model.ActiveUser == null)
            {
                <a asp-area="Identity" asp-page="/Account/Register" asp-route-returnUrl="@Context.Request.Path"> <img src="~/icons/RatingIcon.svg"/></a>
                <div class="rating">@post.Rating</div>
                <a asp-area="Identity" asp-page="/Account/Register" asp-route-returnUrl="@Context.Request.Path"> <img src="~/icons/RatingIcon.svg"/> </a>
            }
            else
            {
                @if (Model.UpvotedPostsIds.Contains(post.Id))
                {
                    @(await Html.RenderComponentAsync<CourseWorkSpring2023.BlazorComponents.
                        RatingBtns>(RenderMode.ServerPrerendered,new { UserId = Model.ActiveUser.Id, ContentId = post.Id, Rating = post.Rating, ISPostLiked = true }))
                }
                else if (Model.DownvotedPostsIds.Contains(post.Id))
                {
                    @(await Html.RenderComponentAsync<CourseWorkSpring2023.BlazorComponents.
                        RatingBtns>(RenderMode.ServerPrerendered,new { UserId = Model.ActiveUser.Id, ContentId = post.Id, Rating = post.Rating, IsPostDisLiked = true }))
                }
                else
                    {
                        @(await Html.RenderComponentAsync<CourseWorkSpring2023.BlazorComponents.
                        RatingBtns>(RenderMode.ServerPrerendered,new { UserId = Model.ActiveUser.Id, ContentId = post.Id, Rating = post.Rating }))
                    }
                }
            </div>
            <a class="custom-post-open custom-red_btn" asp-action="ReadPost" asp-route-postId=@post.Id>Открыть</a>
        </div>
    }
</div>

<a href="#logo" class="custom-go_top_btn custom-red_btn">
    Наверх
</a>

@section scripts{
    <script src="~/js/CommonActions/ratings.js"></script>
    <script src="~/js/PostsFilter/posts_filter.js"></script>
}

Views/Posts/PostFilterDates.cshtml
<div>
    <a class="component-post_filter_btn custom-red_btn">Лучшие</a>

<div class="component-post_filter">
    <a class="custom-red_btn" asp-action="Index" asp-controller="Posts" asp-route-filter="top" asp-route-days="1">За день</a>
    <a class="custom-red_btn" asp-action="Index" asp-controller="Posts" asp-route-filter="top" asp-route-days="3">За три дня</a>
    <a class="custom-red_btn" asp-action="Index" asp-controller="Posts" asp-route-filter="top" asp-route-days="7">За неделю</a>
</div>

</div>

Views/Posts/ReadPost.cshtml
@using CourseWorkSpring2023.Models.IndexViewModel;
@using CourseWorkSpring2023.Models.Moderator;
@model PostViewModel

@{
    string retUrl = Context.Request.Path + Context.Request.QueryString;
}
<div class="custom-post_strip">
    <div>
        <div>@Model.Header</div>
            <div class="custom-rate-btns">
                        @if(Model.ActiveUser == null)
                        {
                            <a class="" asp-area="Identity" asp-page="/Account/Register" asp-route-returnUrl="@retUrl"> <img src="~/icons/RatingIcon.svg"/></a>
                            <div class="rating">@Model.Rating</div>
                            <a class="" asp-area="Identity" asp-page="/Account/Register" asp-route-returnUrl="@retUrl"> <img src="~/icons/RatingIcon.svg"/> </a>
                        }
                        else
                        {
                            @if (Model.UpvotedCommentsIds.Contains(Model.Id))
                            {
                                @(await Html.RenderComponentAsync<CourseWorkSpring2023.BlazorComponents.
                                RatingBtns>(RenderMode.ServerPrerendered,new { UserId = Model.ActiveUser.Id, ContentId = Model.Id, Rating = Model.Rating, ISPostLiked = true }))
                            }
                            else if (Model.DownvotedCommentsIds.Contains(Model.Id))
                            {
                                @(await Html.RenderComponentAsync<CourseWorkSpring2023.BlazorComponents.
                                RatingBtns>(RenderMode.ServerPrerendered,new { UserId = Model.ActiveUser.Id, ContentId = Model.Id, Rating = Model.Rating, IsPostDisLiked = true }))
                            }
                            else
                            {
                                @(await Html.RenderComponentAsync<CourseWorkSpring2023.BlazorComponents.
                                RatingBtns>(RenderMode.ServerPrerendered,new { UserId = Model.ActiveUser.Id, ContentId = Model.Id, Rating = Model.Rating }))
                            }
                        }
            </div>
    </div>
    <div>
        <div class="custom-strip_author">
                <img class="custom-greet_img" src="@Model.UserAvatar" />
                @Html.ActionLink(@Model.Author.NickName, "UserPage", "User", new { userName = Model.Author.UserName})
        </div>
        <div>@Html.ActionLink("Закрыть", "Index", "Posts")</div>
    </div>
</div>

<div class="custom-posts_container">
    <div class="custom-post_header">
        <h1>@Model.Header</h1>
        <div>@Model.Posted</div>
</div>

    <div class="custom-post_text">
        @Model.ProcessedText
    </div>

    <textarea id="text_input"></textarea>
    <p>Комментариев - @Model.CommentsCount</p>

    @if(Model.ActiveUser == null){
        <a class="custom-red_btn custom-leave_message_unsigned" asp-area="Identity" asp-page="/Account/Register" asp-route-returnUrl="@retUrl">Оставить комментарий</a>
    }
    else{
        @(await Html.RenderComponentAsync<CourseWorkSpring2023.BlazorComponents.
                        CommentBtn>(RenderMode.ServerPrerendered,new { PostId = Model.Id, UserName = User.Identity.Name}))
    }

    <div class="custom-comment_section">
        @if(Model.Comments.Any()){
            @foreach (var comment in Model.Comments)
            {

                <div class="custom-comment" id="@comment.Id">
                    @if (User.IsInRole("Moderator") || User.Identity.Name == Model.Author.Email)
                        @(await Html.RenderComponentAsync<CourseWorkSpring2023.BlazorComponents.ModeratorTools>(RenderMode.ServerPrerendered,new { ContentType = "comment", Id = comment.Id, IsHidden = comment.IsHidden}))
                    
                    <div class="custom-rate-btns">
                        @if(Model.ActiveUser == null)
                        {
                            <a class="" asp-area="Identity" asp-page="/Account/Register" asp-route-returnUrl="@retUrl"> <img src="~/icons/RatingIcon.svg"/></a>
                            <div class="rating">@comment.Rating</div>
                            <a class="" asp-area="Identity" asp-page="/Account/Register" asp-route-returnUrl="@retUrl"> <img src="~/icons/RatingIcon.svg"/> </a>
                        }
                        else
                        {
                            @if (Model.UpvotedCommentsIds.Contains(comment.Id))
                            {
                                @(await Html.RenderComponentAsync<CourseWorkSpring2023.BlazorComponents.
                                RatingBtns>(RenderMode.ServerPrerendered,new { UserId = Model.ActiveUser.Id, ContentId = comment.Id, Rating = comment.Rating, ISPostLiked = true }))
                            }
                            else if (Model.DownvotedCommentsIds.Contains(comment.Id))
                            {
                                @(await Html.RenderComponentAsync<CourseWorkSpring2023.BlazorComponents.
                                RatingBtns>(RenderMode.ServerPrerendered,new { UserId = Model.ActiveUser.Id, ContentId = comment.Id, Rating = comment.Rating, IsPostDisLiked = true }))
                            }
                            else
                            {
                                @(await Html.RenderComponentAsync<CourseWorkSpring2023.BlazorComponents.
                                RatingBtns>(RenderMode.ServerPrerendered,new { UserId = Model.ActiveUser.Id, ContentId = comment.Id, Rating = comment.Rating }))
                            }
                        }
                    </div>

                    <div>
                        <div class="custom-comment_info">
                            <img class="custom-greet_img" src="@comment.UserAvatarPath">
                            <div>@Html.ActionLink(comment.User.NickName, "UserPage", "Home", new { userName = comment.User.UserName})</div>
                            <div>@comment.Uploaded</div>
                        </div>
                        <div>@comment.ProcessedText</div>
                    </div>
                </div>
            }
        }else{
            <div class="no-comments">
                <p>Комментариев пока нету</p>
            </div>
        }    
        </div>
</div>


@section scripts{
    <script src="~/lib/Trumbowyg/dist/trumbowyg.min.js"></script>
    <script src="~/lib/Trumbowyg/dist/langs/ru.js"></script>
    <script src="~/js/RichTextArea/rich_text_area.js"></script>
    <script src="~/js/Blazor/BlazorHandler.js"></script>
    <script src="~/js/fixedStrip.js"></script>
}

@section AddToHead{
    <link rel="stylesheet" href="~/lib/Trumbowyg/dist/ui/trumbowyg.min.css">
    <link rel="stylesheet" href="~/css/post_page.css"/>
}